### ISSUE TITLE
修改聚类设定值会报错

### ISSUE THREAD

**Issue by zidong6344** [FlorentF9/skstab#1]
将聚类设定值k_values修改为从2开始会报错，是必须从1开始么？

**Comment by FlorentF9** [comment]
I will answer in english: it has to start from 1 only if you use the "crossing" strategy for model selection, as you can see from the README example:
`score = stab.score(strategy='max', crossing=True)`
In this method we use the stability curve of K=1 to determine the maximum amount of perturbation that can be applied before destroying the cluster structure. However if you use `crossing=False`, you can start at K=2 or any value, but you should verify that the amount of perturbation added is not too large.

**Comment by zidong6344** [comment]
i get
