### ISSUE TITLE
Experience sharing_how to setup skstab

### ISSUE THREAD

**Issue by SolaCloud** [FlorentF9/skstab#2]
1. download the zip, unzip and put the whole file in the site-packages file under anaconda; **mine** is C:\Users\**Sola**\anaconda3\Lib\site-packages;
2. run the cmd as administrator, direct the path to the 'skstab-master' file location (as above) using command: cd C:\Users\Sola\anaconda3\Lib\site-packages\skstab-master
3. run the python file using code: python setup.py install
4. when you finished, you will see: Finished processing dependencies for skstab==0.1b0. 

Thanks for the package!

**Comment by FlorentF9** [comment]
Thanks for you kind support! 
(for step 1, I rather recommend to `git clone` the repo, in order to benefit from version control and easily pull the latest updates)
