### ISSUE TITLE
Single cluster error

### ISSUE THREAD

**Issue by jbschiratti** [FlorentF9/skstab#3]
In an experiment, I've been using the `StadionEstimator` with KMeans, similarly to what is done in [example_stadion.py](https://github.com/FlorentF9/skstab/blob/master/example_stadion.py). Selecting the "optimal" number of clusters using:
```python
k_hat = stab.select_param()[0]
print('Selected number of clusters: K =', k_hat)
```
always fails with the error:
```python
File skstab/skstab/stability.py:475, in StadionEstimator._find_crossing(stadion_paths, param_values, y_ref)
    472 k1_idx = np.array([i for i in range(len(param_values))
    473                    if (y_ref[param_values[i]] == 0).all()])  # indices where K=1
    474 if k1_idx.size == 0:
--> 475     raise ValueError("no path corresponding to a single cluster (K=1)!")
    476 score_ = np.delete(stadion_paths, k1_idx, axis=0)
    477 k1 = k1_idx[0]  # k1 corresponds to the first index where K=1

ValueError: no path corresponding to a single cluster (K=1)!
```
Should `crossing=False` be passed to `select_param` to avoid this error? Is there another way to circumvent it?

**Comment by FlorentF9** [comment]
Have you included K=1 in the parameters to evaluate? (`k_values` in the example).
If not, the "crossing"technique cannot be used, in this case you should set `crossing=False`.
